### ISSUE TITLE
Why is this repo private?

### ISSUE THREAD

**Issue by sparrell** [OpenC2-org/openc2-yuuki#1]
This repo was created to allow a public repo (https://github.com/jtcb/yuuki) to be cloned into openC2 space. Since the original is public, why is this private?

I realize I hammer on the transparency issue wrt openC2 but the govvies really need to change their [skeuomorph](https://brown.edu/Departments/Joukowsky_Institute/courses/greekpast/4697.html) (outdated design practice no longer applicable - in this case "starting private") if they want to be "open".

**Comment by romanojd** [comment]
Sorry. That was just the default. I switched it over to public. Thanks for the catch.
